openapi: 3.0.0
info:
  title: Микросервис Заявка
  description: API для обработки заявок на кредит
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /statement:
    post:
      summary: Прескоринг + запрос на расчет возможных условий кредита
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanStatementRequestDto'
      responses:
        '200':
          description: Список предложений по заявке
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOfferDto'
  /statement/offer:
    post:
      summary: Выбор одного из предложений
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanOfferDto'
      responses:
        '204':
          description: ОК
components:
  schemas:
    LoanStatementRequestDto:
      type: object
      properties:
        amount:
          type: integer
          format: int64
        term:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        email:
          type: string
        birthdate:
          type: string
          format: date-time
        passportNumber:
          type: string
        passportSeries:
          type: string
    LoanOfferDto:
      type: object
      properties:
        requestedAmount:
          type: integer
          format: int64
        totalAmount:
          type: integer
          format: int64
        term:
          type: integer
        monthlyPayment:
          type: number
        rate:
          type: number
        isSalaryClient:
          type: boolean
        isInsuranceEnabled:
          type: boolean