openapi: 3.0.0
info:
  title: Кредитный калькулятор API
  version: 1.0.0
paths:
  /calculator/offers:
    post:
      summary: Расчёт возможных условий кредита
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanStatementRequestDto'
      responses:
        '200':
          description: Список кредитных предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOfferDto'
  /calculator/calc:
    post:
      summary: Валидация данных и расчет параметров кредита
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScoringDataDto'
      responses:
        '200':
          description: Информация о кредитном договоре
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditDto'
components:
  schemas:
    LoanStatementRequestDto:
      type: object
      properties:
        amount:
          type: string
          format: BigDecimal
        term:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        email:
          type: string
        birthdate:
          type: string
          format: date
        passportSeries:
          type: string
        passportNumber:
          type: string
    LoanOfferDto:
      type: object
      properties:
        statementId:
          type: string
          format: uuid
        requestedAmount:
          type: string
          format: BigDecimal
        totalAmount:
          type: string
          format: BigDecimal
        term:
          type: integer
        monthlyPayment:
          type: string
          format: BigDecimal
        rate:
          type: string
          format: BigDecimal
        isInsuranceEnabled:
          type: boolean
        isSalaryClient:
          type: boolean
    ScoringDataDto:
      type: object
      properties:
        amount:
          type: string
          format: BigDecimal
        term:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        gender:
          type: string
          enum: [MALE, FEMALE]
        birthdate:
          type: string
          format: date
        passportSeries:
          type: string
        passportNumber:
          type: string
        passportIssueDate:
          type: string
          format: date
        passportIssueBranch:
          type: string
        maritalStatus:
          type: string
          enum: [SINGLE, MARRIED, DIVORCED]
        dependentAmount:
          type: integer
        employment:
          $ref: '#/components/schemas/EmploymentDto'
        accountNumber:
          type: string
        isInsuranceEnabled:
          type: boolean
        isSalaryClient:
          type: boolean
    CreditDto:
      type: object
      properties:
        amount:
          type: string
          format: BigDecimal
        term:
          type: integer
        monthlyPayment:
          type: string
          format: BigDecimal
        rate:
          type: string
          format: BigDecimal
        psk:
          type: string
          format: BigDecimal
        isInsuranceEnabled:
          type: boolean
        isSalaryClient:
          type: boolean
        paymentSchedule:
          type: array
          items:
            $ref: '#/components/schemas/PaymentScheduleElementDto'
    EmploymentDto:
      type: object
      properties:
        employmentStatus:
          type: string
          enum: [EMPLOYED, SELF_EMPLOYED, UNEMPLOYED]
        employerINN:
          type: string
        salary:
          type: string
          format: BigDecimal
        position:
          type: string
          enum: [MANAGER, ENGINEER, CONSULTANT]
    PaymentScheduleElementDto:
      type: object
      properties:
        number:
          type: integer
        date:
          type: string
          format: date
        totalPayment:
          type: string
          format: BigDecimal
        interestPayment:
          type: string
          format: BigDecimal
        debtPayment:
          type: string
          format: BigDecimal